### ISSUE TITLE
Script not found error.

### ISSUE THREAD

**Issue by muralib2486** [alexandarp/gitops-terraform-jenkins#15]
I get the below error in Jenkins. I am using ubuntu image by the way "ami-0b44050b2d893d5f7" in AP-south-1 region. Suspecting the ami could be the cause. But not sure what script.sh file it is referring to.
I checked the location as per the error and don''t see any script.sh file. 

+ terraform init /var/lib/jenkins/workspace/Terraform_Demo_master@tmp/durable-835b8f4f/script.sh: 1: /var/lib/jenkins/workspace/Terraform_Demo_master@tmp/durable-835b8f4f/script.sh: terraform: not found

**Comment by alexandarp** [comment]
This is a script that is most likely created by Jenkins in the background.

Did you add Terraform to your path?

**Comment by alexandarp** [comment]
If you continue to have issues, please open another issue.

**Comment by rushirg** [comment]
I am also getting this issue. I have added terraform to my PATH. Is this issue related to the permission of /var/lib/jenkins/workspace? Because when I execute `terraform init` it failed to create the `.terraform` the directory. I can see that both the user and group for this directory is jenkins. Am I missing something here?
